# Generated by Django 3.1.4 on 2021-01-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterType', models.CharField(max_length=500)),
                ('groundTruth', models.CharField(max_length=500)),
                ('userChoice', models.CharField(max_length=500)),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('handiness', models.CharField(max_length=20)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=8000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmotionData.user')),
            ],
        ),
    ]
